### ISSUE TITLE
Nullable attributes

### ISSUE THREAD

**Issue by DiV666** [CodelyTV/typescript-primitives-type#6]
Hi,

I have tried to use the library but I have problems with null values.

In a class with some attribute of type `VideoName | null`, the return type is `VideoName | null` when it should be `string | null`

Is it possible to fix this?

Regards

**Comment by ismanapa** [comment]
Hello!

We don't have `null` support because we don't have nulls in our code base right now.

On the other hand, I think that it is possible to implement this case so I invite you to make a PR if you want to add this feature so the utility will grow with the collaboration of the community 😄

Do you want to try it? 🤗

Thanks for all

**Comment by DiV666** [comment]
Of course, I will try, but I can't promise anything :smile:

**Comment by ismanapa** [comment]
I think that this is fixed with this #8 so I am going to close this issue
